# Generated by Django 5.2.12 on 2026-03-28 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('finance', '0004_transaction_school_year'),
        ('groups', '0010_dailyprotocol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titel')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('event_type', models.CharField(choices=[('excursion', 'Ausflug'), ('event', 'Veranstaltung'), ('workshop', 'Workshop'), ('sports', 'Sportveranstaltung'), ('cultural', 'Kulturveranstaltung'), ('other', 'Sonstiges')], default='excursion', max_length=20, verbose_name='Veranstaltungstyp')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('planned', 'Geplant'), ('confirmed', 'Bestaetigt'), ('in_progress', 'Laufend'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt')], default='draft', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(blank=True, help_text='Leer lassen fuer eintaegige Veranstaltungen', null=True, verbose_name='Enddatum')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Startzeit')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Endzeit')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='Veranstaltungsort')),
                ('meeting_point', models.CharField(blank=True, max_length=255, verbose_name='Treffpunkt')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Geschaetzte Kosten')),
                ('cost_per_student', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kosten pro Schueler')),
                ('requires_consent', models.BooleanField(default=True, help_text='Ob eine Einverstaendniserklaerung der Eltern erforderlich ist', verbose_name='Einverstaendnis erforderlich')),
                ('consent_deadline', models.DateField(blank=True, null=True, verbose_name='Einverstaendnis-Frist')),
                ('consent_text', models.TextField(blank=True, help_text='Text der Einverstaendniserklaerung fuer die Eltern', verbose_name='Einverstaendnistext')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('internal_notes', models.TextField(blank=True, help_text='Nur fuer Paedagogen sichtbar', verbose_name='Interne Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('groups', models.ManyToManyField(blank=True, related_name='events', to='groups.group', verbose_name='Teilnehmende Gruppen')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.location', verbose_name='Standort')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='groups.schoolyear', verbose_name='Schuljahr')),
                ('transactions', models.ManyToManyField(blank=True, related_name='events', to='finance.transaction', verbose_name='Verknuepfte Transaktionen')),
            ],
            options={
                'verbose_name': 'Veranstaltung',
                'verbose_name_plural': 'Veranstaltungen',
                'db_table': 'events_event',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_status', models.CharField(choices=[('pending', 'Ausstehend'), ('granted', 'Erteilt'), ('denied', 'Verweigert'), ('not_required', 'Nicht erforderlich')], default='pending', max_length=20, verbose_name='Einverstaendnis-Status')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Einverstaendnis-Datum')),
                ('consent_given_by', models.CharField(blank=True, help_text='Name des Erziehungsberechtigten', max_length=255, verbose_name='Einverstaendnis erteilt von')),
                ('consent_notes', models.TextField(blank=True, verbose_name='Einverstaendnis-Notizen')),
                ('attendance_status', models.CharField(choices=[('registered', 'Angemeldet'), ('attended', 'Teilgenommen'), ('absent', 'Abwesend'), ('cancelled', 'Abgesagt')], default='registered', max_length=20, verbose_name='Teilnahme-Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='Veranstaltung')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_participations', to='groups.student', verbose_name='Schueler/in')),
            ],
            options={
                'verbose_name': 'Veranstaltungsteilnehmer',
                'verbose_name_plural': 'Veranstaltungsteilnehmer',
                'db_table': 'events_eventparticipant',
                'ordering': ['student__last_name', 'student__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['location'], name='events_even_locatio_b471aa_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['event'], name='events_even_event_i_7ee2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['student'], name='events_even_student_159f54_idx'),
        ),
        migrations.AddIndex(
            model_name='eventparticipant',
            index=models.Index(fields=['consent_status'], name='events_even_consent_2994b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'student')},
        ),
    ]
