# Generated by Django 5.2.11 on 2026-03-01 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. 2025/2026', max_length=50, verbose_name='Name')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('is_active', models.BooleanField(default=False, help_text='Nur ein Schuljahr pro Standort kann aktiv sein.', verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_years', to='core.location', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Schuljahr',
                'verbose_name_plural': 'Schuljahre',
                'db_table': 'calendar_schoolyear',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('balance', models.DecimalField(decimal_places=2, default=0, help_text='Aktueller Kontostand der Gruppenkasse in EUR', max_digits=10, verbose_name='Kontostand')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Waehrung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL, verbose_name='Gruppenleitung')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.location', verbose_name='Standort')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.schoolyear', verbose_name='Schuljahr')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppen',
                'db_table': 'groups_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('autumn', 'Herbst'), ('winter', 'Winter'), ('spring', 'Fruehling'), ('summer', 'Sommer')], max_length=50, verbose_name='Semester')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='groups.schoolyear', verbose_name='Schuljahr')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semester',
                'db_table': 'calendar_semester',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Strasse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Stadt')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='groups.group', verbose_name='Gruppe')),
            ],
            options={
                'verbose_name': 'Schueler',
                'verbose_name_plural': 'Schueler',
                'db_table': 'groups_student',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('educator', 'Paedagogin'), ('assistant', 'Assistenz'), ('substitute', 'Vertretung')], default='educator', max_length=20, verbose_name='Rolle in Gruppe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Beigetreten am')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Ausgetreten am')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group', verbose_name='Gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Gruppenmitglied',
                'verbose_name_plural': 'Gruppenmitglieder',
                'db_table': 'groups_groupmember',
                'indexes': [models.Index(fields=['group'], name='groups_grou_group_i_736683_idx'), models.Index(fields=['user'], name='groups_grou_user_id_73c910_idx')],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='schoolyear',
            index=models.Index(fields=['location'], name='calendar_sc_locatio_32d72a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolyear',
            index=models.Index(fields=['is_active'], name='calendar_sc_is_acti_0b3bdf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolyear',
            unique_together={('location', 'name')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['location'], name='groups_grou_locatio_c9cf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['school_year'], name='groups_grou_school__c49949_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['leader'], name='groups_grou_leader__167eaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('location', 'school_year', 'name')},
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['school_year'], name='calendar_se_school__bc6d91_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['group'], name='groups_stud_group_i_776683_idx'),
        ),
    ]
