# Generated by Django 5.2.12 on 2026-03-25 15:44

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id'], 'verbose_name': 'Schueler', 'verbose_name_plural': 'Schueler'},
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=encrypted_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Geburtsdatum'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Strasse'),
        ),
    ]
