# Generated by Django 5.2.12 on 2026-03-25 16:09

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_student_options_alter_student_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, null=True, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, null=True, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Strasse'),
        ),
    ]
