# Generated by Django 5.2.12 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_student_city_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anonymisiert am'),
        ),
    ]
