# Generated by Django 5.2.12 on 2026-03-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_attendance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='groups_atte_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='groups_atte_group_i_35fbd4_idx',
            old_name='groups_atte_group_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='groups_atte_student_ac4912_idx',
            old_name='groups_atte_student_date_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='groups_atte_date_316413_idx',
            old_name='groups_atte_date_status_idx',
        ),
    ]
