# Generated by Django 5.2.12 on 2026-03-28 13:02

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('groups', '0007_remove_attendance_groups_atte_organiz_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateField(verbose_name='Datum des Wechsels')),
                ('start_time', models.TimeField(help_text='Uhrzeit ab der das Kind in der Zielgruppe ist', verbose_name='Beginn')),
                ('end_time', models.TimeField(blank=True, help_text='Uhrzeit bis der das Kind in der Zielgruppe ist (leer = ganzer Tag)', null=True, verbose_name='Ende')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Grund')),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('confirmed', 'Bestaetigt'), ('rejected', 'Abgelehnt'), ('completed', 'Abgeschlossen')], default='pending', max_length=20, verbose_name='Status')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bestaetigt/Abgelehnt am')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Abgeschlossen am')),
                ('notes', models.TextField(blank=True, default='', help_text='Zusaetzliche Notizen zum Gruppenwechsel', verbose_name='Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='Bestaetigt/Abgelehnt von')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Angefragt von')),
                ('source_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='groups.group', verbose_name='Herkunftsgruppe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='groups.student', verbose_name='Schueler/in')),
                ('target_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='groups.group', verbose_name='Zielgruppe')),
            ],
            options={
                'verbose_name': 'Gruppenwechsel',
                'verbose_name_plural': 'Gruppenwechsel',
                'db_table': 'groups_grouptransfer',
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'transfer_date'], name='groups_grou_student_85420f_idx'), models.Index(fields=['source_group', 'transfer_date'], name='groups_grou_source__657fee_idx'), models.Index(fields=['target_group', 'transfer_date'], name='groups_grou_target__05632a_idx'), models.Index(fields=['status'], name='groups_grou_status_c992ff_idx'), models.Index(fields=['-transfer_date', '-created_at'], name='groups_grou_transfe_e37a4b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='Genau eine Kontaktperson pro Schueler muss als Hauptansprechperson markiert sein.', verbose_name='Hauptansprechperson')),
                ('relationship', models.CharField(choices=[('parent', 'Elternteil'), ('uncle', 'Onkel'), ('aunt', 'Tante'), ('grandparent', 'Grosselternteil'), ('relative', 'Verwandte/r'), ('authorized', 'Abholberechtigte Person')], max_length=20, verbose_name='Beziehung')),
                ('first_name', encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Vorname')),
                ('last_name', encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Nachname')),
                ('phone', encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefon')),
                ('email', encrypted_fields.fields.EncryptedEmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-Mail')),
                ('whatsapp_available', models.BooleanField(default=False, verbose_name='WhatsApp verfuegbar')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='groups.student', verbose_name='Schueler/in')),
            ],
            options={
                'verbose_name': 'Kontaktperson',
                'verbose_name_plural': 'Kontaktpersonen',
                'db_table': 'groups_studentcontact',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['student'], name='groups_stud_student_17f97a_idx'), models.Index(fields=['is_primary'], name='groups_stud_is_prim_22d1b9_idx')],
            },
        ),
    ]
