# Generated by Django 5.2.12 on 2026-03-28 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('groups', '0008_grouptransfer_studentcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Schulautonomer Tag, Pädagogischer Tag', max_length=100, verbose_name='Bezeichnung')),
                ('date', models.DateField(verbose_name='Datum')),
                ('description', models.TextField(blank=True, help_text='Optionale Beschreibung oder Begründung', verbose_name='Beschreibung')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autonomous_days', to='groups.schoolyear', verbose_name='Schuljahr')),
            ],
            options={
                'verbose_name': 'Schulautonomer Tag',
                'verbose_name_plural': 'Schulautonome Tage',
                'db_table': 'calendar_autonomous_day',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['school_year'], name='calendar_au_school__3a5c18_idx'), models.Index(fields=['date'], name='calendar_au_date_d053b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='HolidayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='z.B. Weihnachtsferien, Semesterferien, Osterferien', max_length=100, verbose_name='Bezeichnung')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='groups.schoolyear', verbose_name='Schuljahr')),
            ],
            options={
                'verbose_name': 'Ferienzeit',
                'verbose_name_plural': 'Ferienzeiten',
                'db_table': 'calendar_holiday_period',
                'ordering': ['start_date'],
                'indexes': [models.Index(fields=['school_year'], name='calendar_ho_school__4053ae_idx'), models.Index(fields=['start_date', 'end_date'], name='calendar_ho_start_d_f94646_idx')],
            },
        ),
    ]
