# Generated by Django 5.2.12 on 2026-03-28 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('groups', '0009_autonomousday_holidayperiod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Ankunftszeit')),
                ('arrival_notes', models.TextField(blank=True, default='', help_text='z.B. von wem gebracht, Besonderheiten bei Ankunft.', verbose_name='Ankunft-Notizen')),
                ('incidents', models.TextField(blank=True, default='', verbose_name='Besondere Vorkommnisse')),
                ('incident_severity', models.CharField(choices=[('normal', 'Normal'), ('important', 'Wichtig'), ('urgent', 'Dringend')], default='normal', max_length=20, verbose_name='Schweregrad')),
                ('pickup_time', models.TimeField(blank=True, null=True, verbose_name='Abholzeit')),
                ('pickup_notes', models.TextField(blank=True, default='', verbose_name='Abhol-Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('effective_group', models.ForeignKey(blank=True, help_text='Falls der Schueler an diesem Tag die Gruppe gewechselt hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effective_daily_protocols', to='groups.group', verbose_name='Tatsaechliche Gruppe')),
                ('group', models.ForeignKey(help_text='Die Stammgruppe des Schuelers.', on_delete=django.db.models.deletion.CASCADE, related_name='daily_protocols', to='groups.group', verbose_name='Hauptgruppe')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('picked_up_by', models.ForeignKey(blank=True, help_text='Kontaktperson die das Kind abgeholt hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='groups.studentcontact', verbose_name='Abgeholt von')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_protocols', to=settings.AUTH_USER_MODEL, verbose_name='Erfasst von')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_protocols', to='groups.schoolyear', verbose_name='Schuljahr')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_protocols', to='groups.student', verbose_name='Schueler/in')),
                ('transfer', models.ForeignKey(blank=True, help_text='Verknuepfung zum Gruppenwechsel, falls vorhanden.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_protocols', to='groups.grouptransfer', verbose_name='Gruppenwechsel')),
            ],
            options={
                'verbose_name': 'Tagesprotokoll',
                'verbose_name_plural': 'Tagesprotokolle',
                'db_table': 'groups_dailyprotocol',
                'ordering': ['-date', 'student__last_name'],
                'indexes': [models.Index(fields=['student', 'date'], name='groups_dail_student_abf553_idx'), models.Index(fields=['group', 'date'], name='groups_dail_group_i_75fef4_idx'), models.Index(fields=['date'], name='groups_dail_date_4282ac_idx'), models.Index(fields=['incident_severity'], name='groups_dail_inciden_0ffae9_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
