# Generated by Django 5.2.12 on 2026-03-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_add_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_org_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='attendance',
            name='att_org_grp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyprotocol',
            name='proto_org_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='dailyprotocol',
            name='proto_org_grp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='student',
            name='student_org_grp_idx',
        ),
    ]
