# Generated by Django 5.2.12 on 2026-03-30 05:32

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_remove_attendance_att_org_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_consent_date',
            field=models.DateField(blank=True, help_text='Datum der Einwilligung durch den Erziehungsberechtigten', null=True, verbose_name='Einwilligungsdatum'),
        ),
        migrations.AddField(
            model_name='student',
            name='data_consent_document',
            field=models.FileField(blank=True, help_text='Hochgeladenes Einwilligungsformular (PDF/Scan)', null=True, upload_to='consent_documents/%Y/%m/', verbose_name='Einwilligungsdokument'),
        ),
        migrations.AddField(
            model_name='student',
            name='data_consent_guardian_name',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', help_text='Name der Person, die die Einwilligung erteilt hat', max_length=255, null=True, verbose_name='Name des Erziehungsberechtigten'),
        ),
        migrations.AddField(
            model_name='student',
            name='data_consent_status',
            field=models.CharField(choices=[('pending', 'Ausstehend'), ('granted', 'Erteilt'), ('revoked', 'Widerrufen')], default='pending', help_text='Status der Einwilligung zur Datenverarbeitung (Art. 8 DSGVO)', max_length=20, verbose_name='Einwilligungsstatus'),
        ),
        migrations.AddField(
            model_name='student',
            name='processing_restricted',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, duerfen die Daten nur gespeichert, aber nicht verarbeitet werden (Art. 18 DSGVO)', verbose_name='Verarbeitung eingeschraenkt'),
        ),
        migrations.AddField(
            model_name='student',
            name='restriction_date',
            field=models.DateField(blank=True, help_text='Datum, seit dem die Verarbeitung eingeschraenkt ist', null=True, verbose_name='Einschraenkung seit'),
        ),
        migrations.AddField(
            model_name='student',
            name='restriction_reason',
            field=models.TextField(blank=True, default='', help_text='Grund fuer die Einschraenkung der Verarbeitung', verbose_name='Grund der Einschraenkung'),
        ),
    ]
