# Generated by Django 5.2.12 on 2026-03-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_student_data_consent_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='data_consent_guardian_name',
            field=models.CharField(blank=True, default='', help_text='Name der Person, die die Einwilligung erteilt hat', max_length=255, verbose_name='Name des Erziehungsberechtigten'),
        ),
    ]
