# Generated by Django 5.2.11 on 2026-02-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Schlüssel')),
                ('value', models.TextField(verbose_name='Wert')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_public', models.BooleanField(default=False, verbose_name='Öffentlich')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Systemeinstellung',
                'verbose_name_plural': 'Systemeinstellungen',
                'db_table': 'system_setting',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Erstellt'), ('update', 'Aktualisiert'), ('delete', 'Gelöscht'), ('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('approve', 'Genehmigt'), ('reject', 'Abgelehnt')], max_length=20, verbose_name='Aktion')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modell')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='Objekt-ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Änderungen')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-Adresse')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Audit-Log',
                'verbose_name_plural': 'Audit-Logs',
                'db_table': 'system_auditlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='system_audi_user_id_56ee2a_idx'), models.Index(fields=['action'], name='system_audi_action_ffdcc8_idx'), models.Index(fields=['model_name'], name='system_audi_model_n_df3200_idx'), models.Index(fields=['-created_at'], name='system_audi_created_bb9a41_idx')],
            },
        ),
    ]
