# Generated by Django 5.2.12 on 2026-03-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('new_user_created', 'Neuer Benutzer erstellt'), ('password_changed', 'Passwort geändert'), ('password_reset', 'Passwort zurückgesetzt'), ('login_new_device', 'Login von neuem Gerät'), ('2fa_enabled', '2FA aktiviert'), ('2fa_disabled', '2FA deaktiviert'), ('transaction_created', 'Transaktion erstellt'), ('transaction_approved', 'Transaktion genehmigt'), ('transaction_rejected', 'Transaktion abgelehnt'), ('leave_request_created', 'Urlaubsantrag erstellt'), ('leave_request_approved', 'Urlaubsantrag genehmigt'), ('leave_request_rejected', 'Urlaubsantrag abgelehnt'), ('terms_accepted', 'Nutzungsbedingungen akzeptiert'), ('system_alert', 'System-Warnung')], max_length=50, unique=True, verbose_name='Ereignistyp')),
                ('is_enabled', models.BooleanField(default=True, help_text='Ob E-Mail-Benachrichtigungen für dieses Ereignis gesendet werden.', verbose_name='Aktiviert')),
                ('notify_super_admins', models.BooleanField(default=True, help_text='Ob Super-Admins bei diesem Ereignis per E-Mail benachrichtigt werden.', verbose_name='Super-Admins benachrichtigen')),
                ('notify_user', models.BooleanField(default=True, help_text='Ob der betroffene Benutzer per E-Mail benachrichtigt wird.', verbose_name='Betroffenen Benutzer benachrichtigen')),
                ('custom_recipients', models.TextField(blank=True, help_text='Kommagetrennte E-Mail-Adressen für zusätzliche Benachrichtigungen.', verbose_name='Zusätzliche Empfänger')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'E-Mail-Benachrichtigung',
                'verbose_name_plural': 'E-Mail-Benachrichtigungen',
                'db_table': 'system_email_notification_config',
                'ordering': ['event_type'],
            },
        ),
    ]
