# Generated by Django 5.2.12 on 2026-03-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_org_type_organization_parent_and_more'),
        ('system', '0002_add_email_notification_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Erstellt'), ('update', 'Aktualisiert'), ('delete', 'Geloescht'), ('login', 'Anmeldung'), ('logout', 'Abmeldung'), ('approve', 'Genehmigt'), ('reject', 'Abgelehnt')], max_length=20, verbose_name='Aktion'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, verbose_name='Aenderungen'),
        ),
        migrations.AlterField(
            model_name='emailnotificationconfig',
            name='custom_recipients',
            field=models.TextField(blank=True, help_text='Kommagetrennte E-Mail-Adressen fuer zusaetzliche Benachrichtigungen.', verbose_name='Zusaetzliche Empfaenger'),
        ),
        migrations.AlterField(
            model_name='emailnotificationconfig',
            name='event_type',
            field=models.CharField(choices=[('new_user_created', 'Neuer Benutzer erstellt'), ('password_changed', 'Passwort geaendert'), ('password_reset', 'Passwort zurueckgesetzt'), ('login_new_device', 'Login von neuem Geraet'), ('2fa_enabled', '2FA aktiviert'), ('2fa_disabled', '2FA deaktiviert'), ('transaction_created', 'Transaktion erstellt'), ('transaction_approved', 'Transaktion genehmigt'), ('transaction_rejected', 'Transaktion abgelehnt'), ('leave_request_created', 'Urlaubsantrag erstellt'), ('leave_request_approved', 'Urlaubsantrag genehmigt'), ('leave_request_rejected', 'Urlaubsantrag abgelehnt'), ('terms_accepted', 'Nutzungsbedingungen akzeptiert'), ('system_alert', 'System-Warnung')], max_length=50, unique=True, verbose_name='Ereignistyp'),
        ),
        migrations.AlterField(
            model_name='emailnotificationconfig',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Ob E-Mail-Benachrichtigungen fuer dieses Ereignis gesendet werden.', verbose_name='Aktiviert'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Oeffentlich'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=255, verbose_name='Schluessel'),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('organization', 'key')},
        ),
    ]
