# Generated by Django 5.2.12 on 2026-03-29 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('system', '0003_auditlog_organization_systemsetting_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('notification_type', models.CharField(choices=[('task_status_changed', 'Aufgabenstatus geändert'), ('task_assigned', 'Aufgabe zugewiesen'), ('task_overdue', 'Aufgabe überfällig')], default='task_status_changed', max_length=30, verbose_name='Typ')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Gelesen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Empfänger')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
