# Generated by Django 5.2.12 on 2026-03-29 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_inappnotification'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inappnotification',
            name='related_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tasks.task', verbose_name='Zugehörige Aufgabe'),
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'),
        ),
    ]
