# Generated by Django 5.2.12 on 2026-03-29 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_add_organization_to_user'),
        ('groups', '0012_remove_attendance_att_org_date_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('status', models.CharField(choices=[('open', 'Offen'), ('in_progress', 'In Arbeit'), ('done', 'Erledigt')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niedrig'), ('medium', 'Mittel'), ('high', 'Hoch')], default='medium', max_length=10, verbose_name='Priorität')),
                ('due_date', models.DateField(verbose_name='Stichtag')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Erledigt am')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Zugewiesen an')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='groups.group', verbose_name='Gruppe')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.location', verbose_name='Standort')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Aufgabe',
                'verbose_name_plural': 'Aufgaben',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='task_org_status_idx'), models.Index(fields=['organization', 'assigned_to'], name='task_org_assigned_idx'), models.Index(fields=['organization', 'due_date'], name='task_org_due_idx'), models.Index(fields=['organization', 'created_by'], name='task_org_creator_idx')],
            },
        ),
    ]
