# Generated by Django 5.2.11 on 2026-03-01 08:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('category_type', models.CharField(choices=[('income', 'Einnahme'), ('expense', 'Ausgabe')], max_length=20, verbose_name='Kategorie-Typ')),
                ('is_system_category', models.BooleanField(default=False, help_text='Systemkategorien können nicht gelöscht werden.', verbose_name='Systemkategorie')),
                ('color', models.CharField(default='#000000', help_text='Hex-Farbcode (z.B. #FF5733)', max_length=7, verbose_name='Farbe')),
                ('icon', models.CharField(blank=True, help_text='Lucide Icon-Name', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Transaktionskategorie',
                'verbose_name_plural': 'Transaktionskategorien',
                'db_table': 'finance_transactioncategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='receipts/%Y/%m/', verbose_name='Datei')),
                ('file_name', models.CharField(max_length=255, verbose_name='Dateiname')),
                ('file_size', models.IntegerField(help_text='Dateigroesse in Bytes', verbose_name='Dateigroesse')),
                ('file_type', models.CharField(help_text='MIME-Type (z.B. image/jpeg, application/pdf)', max_length=50, verbose_name='Dateityp')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Hochgeladen von')),
            ],
            options={
                'verbose_name': 'Beleg',
                'verbose_name_plural': 'Belege',
                'db_table': 'finance_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Betrag')),
                ('transaction_type', models.CharField(choices=[('income', 'Einnahme'), ('expense', 'Ausgabe')], max_length=20, verbose_name='Transaktionstyp')),
                ('transaction_date', models.DateField(verbose_name='Transaktionsdatum')),
                ('transaction_time', models.TimeField(blank=True, null=True, verbose_name='Transaktionszeit')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Genehmigungsnotizen')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
            ],
            options={
                'verbose_name': 'Transaktion',
                'verbose_name_plural': 'Transaktionen',
                'db_table': 'finance_transaction',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
