# Generated by Django 5.2.11 on 2026-03-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='groups.group', verbose_name='Gruppe'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='finance.transaction', verbose_name='Transaktion'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to='core.location', verbose_name='Standort'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finance.transactioncategory', verbose_name='Kategorie'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['transaction'], name='finance_rec_transac_717f43_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['uploaded_by'], name='finance_rec_uploade_7c7f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['location'], name='finance_tra_locatio_224e4e_idx'),
        ),
        migrations.AddIndex(
            model_name='transactioncategory',
            index=models.Index(fields=['category_type'], name='finance_tra_categor_5c3317_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactioncategory',
            unique_together={('location', 'name', 'category_type')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['group'], name='finance_tra_group_i_b8f172_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='finance_tra_categor_bbdf49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='finance_tra_created_12c6d1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='finance_tra_status_0941b9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_date'], name='finance_tra_transac_0cc58e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['group', 'status', 'transaction_date'], name='finance_tra_group_i_3f219d_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
    ]
