# Generated by Django 5.2.12 on 2026-03-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_org_type_organization_parent_and_more'),
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Geloescht'),
        ),
        migrations.AlterField(
            model_name='transactioncategory',
            name='is_system_category',
            field=models.BooleanField(default=False, help_text='Systemkategorien koennen nicht geloescht werden.', verbose_name='Systemkategorie'),
        ),
    ]
