# Generated by Django 5.2.12 on 2026-03-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_receipt_organization_transaction_organization_and_more'),
        ('groups', '0009_autonomousday_holidayperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='school_year',
            field=models.ForeignKey(blank=True, help_text='Zugehöriges Schuljahr (wird automatisch zugeordnet)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='groups.schoolyear', verbose_name='Schuljahr'),
        ),
    ]
