# Generated by Django 5.2.12 on 2026-03-30 08:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_transaction_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/%Y/%m/', validators=[core.validators.FileTypeValidator({'application/pdf': ['.pdf'], 'image/jpeg': ['.jpg', '.jpeg'], 'image/png': ['.png'], 'image/webp': ['.webp']}), core.validators.FileSizeValidator(10485760)], verbose_name='Datei'),
        ),
    ]
