# Generated by Django 5.2.12 on 2026-03-27 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_location_city_postal_unencrypted'),
        ('groups', '0005_group_organization_groupmember_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(blank=True, help_text='Montag der Kalenderwoche (leer bei Vorlagen)', null=True, verbose_name='Wochenbeginn (Montag)')),
                ('title', models.CharField(blank=True, help_text="Optionaler Titel (z.B. 'Projektwoche Natur')", max_length=255, verbose_name='Titel')),
                ('notes', models.TextField(blank=True, verbose_name='Anmerkungen')),
                ('is_template', models.BooleanField(default=False, help_text='Markiert diesen Plan als wiederverwendbare Vorlage', verbose_name='Ist Vorlage')),
                ('template_name', models.CharField(blank=True, help_text='Name der Vorlage (nur relevant wenn is_template=True)', max_length=255, verbose_name='Vorlagenname')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_weekly_plans', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('group', models.ForeignKey(blank=True, help_text='Zugehörige Gruppe (leer bei Vorlagen ohne Gruppenbindung)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_plans', to='groups.group', verbose_name='Gruppe')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='core.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Wochenplan',
                'verbose_name_plural': 'Wochenpläne',
                'ordering': ['-week_start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPlanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag')], verbose_name='Wochentag')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('activity', models.CharField(help_text="Name der Aktivität (z.B. 'Morgenkreis', 'Freispiel')", max_length=255, verbose_name='Aktivität')),
                ('description', models.TextField(blank=True, help_text='Optionale Details zur Aktivität', verbose_name='Beschreibung')),
                ('color', models.CharField(blank=True, help_text="Hex-Farbcode (z.B. '#3B82F6'). Wird automatisch aus Kategorie gesetzt.", max_length=7, verbose_name='Farbe')),
                ('category', models.CharField(choices=[('lernen', 'Lernen'), ('bewegung', 'Bewegung'), ('kreativ', 'Kreativ'), ('essen', 'Essen'), ('freizeit', 'Freizeit'), ('musik', 'Musik'), ('natur', 'Natur'), ('sozial', 'Soziales Lernen'), ('ruhe', 'Ruhezeit'), ('sonstiges', 'Sonstiges')], default='sonstiges', max_length=50, verbose_name='Kategorie')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='weeklyplans.weeklyplan', verbose_name='Wochenplan')),
            ],
            options={
                'verbose_name': 'Wochenplan-Eintrag',
                'verbose_name_plural': 'Wochenplan-Einträge',
                'ordering': ['day_of_week', 'start_time', 'sort_order'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['week_start_date'], name='weeklyplans_week_st_560843_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['is_template'], name='weeklyplans_is_temp_a70fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['status'], name='weeklyplans_status_6ad513_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplan',
            index=models.Index(fields=['group', 'week_start_date'], name='weeklyplans_group_i_607786_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyplanentry',
            index=models.Index(fields=['weekly_plan', 'day_of_week'], name='weeklyplans_weekly__3c6471_idx'),
        ),
    ]
