# Generated by Django 5.2.12 on 2026-03-28 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_remove_attendance_groups_atte_organiz_idx_and_more'),
        ('weeklyplans', '0002_weeklyplan_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyplan',
            name='school_year',
            field=models.ForeignKey(blank=True, help_text='Zugehöriges Schuljahr', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_plans', to='groups.schoolyear', verbose_name='Schuljahr'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='weekly_theme',
            field=models.TextField(blank=True, help_text='Übergreifendes Wochenthema oder besondere Aktivitäten (Rich-Text/HTML)', verbose_name='Thema der Woche'),
        ),
        migrations.AlterField(
            model_name='weeklyplanentry',
            name='activity',
            field=models.TextField(help_text='Name/Inhalt der Aktivität (Rich-Text/HTML unterstützt)', verbose_name='Aktivität'),
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Montag'), (1, 'Dienstag'), (2, 'Mittwoch'), (3, 'Donnerstag'), (4, 'Freitag')], verbose_name='Wochentag')),
                ('content', models.TextField(blank=True, help_text='Detaillierte Aktivitätsbeschreibung für diesen Tag (Rich-Text/HTML)', verbose_name='Tagesaktivität')),
                ('weekly_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='weeklyplans.weeklyplan', verbose_name='Wochenplan')),
            ],
            options={
                'verbose_name': 'Tagesaktivität',
                'verbose_name_plural': 'Tagesaktivitäten',
                'ordering': ['day_of_week'],
                'indexes': [models.Index(fields=['weekly_plan', 'day_of_week'], name='weeklyplans_weekly__9f0d21_idx')],
                'unique_together': {('weekly_plan', 'day_of_week')},
            },
        ),
    ]
