# Generated by Django 5.2.11 on 2026-03-01 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='Genehmigung erforderlich')),
                ('max_days_per_year', models.IntegerField(blank=True, help_text='Maximale Anzahl an Tagen pro Jahr (leer = unbegrenzt)', null=True, verbose_name='Max. Tage pro Jahr')),
                ('is_system_type', models.BooleanField(default=False, help_text='Systemtypen koennen nicht geloescht werden.', verbose_name='Systemtyp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='core.location', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Abwesenheitstyp',
                'verbose_name_plural': 'Abwesenheitstypen',
                'db_table': 'timetracking_leavetype',
                'ordering': ['name'],
                'unique_together': {('location', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkingHoursLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_hours_per_week', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='Max. Stunden pro Woche')),
                ('max_hours_per_day', models.DecimalField(decimal_places=2, default=8, max_digits=5, verbose_name='Max. Stunden pro Tag')),
                ('min_break_duration_minutes', models.IntegerField(default=30, verbose_name='Min. Pausendauer (Minuten)')),
                ('min_break_after_hours', models.DecimalField(decimal_places=2, default=6, help_text='Nach wie vielen Stunden eine Pause erforderlich ist', max_digits=5, verbose_name='Pause nach Stunden')),
                ('require_break_confirmation', models.BooleanField(default=False, verbose_name='Pausenbestaetigung erforderlich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_limit', to='core.location', verbose_name='Standort')),
            ],
            options={
                'verbose_name': 'Arbeitszeitgrenze',
                'verbose_name_plural': 'Arbeitszeitgrenzen',
                'db_table': 'timetracking_workinghourslimit',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(verbose_name='Enddatum')),
                ('total_days', models.IntegerField(default=1, editable=False, help_text='Berechnet aus Enddatum - Startdatum + 1', verbose_name='Gesamttage')),
                ('reason', models.TextField(verbose_name='Begruendung')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('pending', 'Ausstehend'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt'), ('cancelled', 'Storniert')], default='pending', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Genehmigt am')),
                ('approval_notes', models.TextField(blank=True, verbose_name='Genehmigungsnotizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Genehmigt von')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
                ('leave_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='timetracking.leavetype', verbose_name='Abwesenheitstyp')),
            ],
            options={
                'verbose_name': 'Abwesenheitsantrag',
                'verbose_name_plural': 'Abwesenheitsantraege',
                'db_table': 'timetracking_leaverequest',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user'], name='timetrackin_user_id_a59137_idx'), models.Index(fields=['leave_type'], name='timetrackin_leave_t_b043f6_idx'), models.Index(fields=['status'], name='timetrackin_status_d52202_idx'), models.Index(fields=['start_date'], name='timetrackin_start_d_7b7ae4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('start_time', models.TimeField(verbose_name='Startzeit')),
                ('end_time', models.TimeField(verbose_name='Endzeit')),
                ('duration_minutes', models.IntegerField(default=0, editable=False, help_text='Berechnet aus Endzeit - Startzeit', verbose_name='Dauer (Minuten)')),
                ('notes', models.TextField(blank=True, verbose_name='Notizen')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Geloescht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='groups.group', verbose_name='Gruppe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Zeiteintrag',
                'verbose_name_plural': 'Zeiteintraege',
                'db_table': 'timetracking_timeentry',
                'ordering': ['-date', '-start_time'],
                'indexes': [models.Index(fields=['user'], name='timetrackin_user_id_adc291_idx'), models.Index(fields=['group'], name='timetrackin_group_i_9c0d77_idx'), models.Index(fields=['date'], name='timetrackin_date_7d698b_idx'), models.Index(fields=['user', 'date'], name='timetrackin_user_id_e99a43_idx')],
            },
        ),
    ]
