# Generated by Django 5.2.11 on 2026-02-28 14:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('postal_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('country', models.CharField(default='Österreich', max_length=100, verbose_name='Land')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'db_table': 'users_organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('educator', 'Pädagogin'), ('location_manager', 'Standortleitung'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='educator', max_length=20, verbose_name='Rolle')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profilbild')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('last_password_change', models.DateTimeField(blank=True, null=True, verbose_name='Letzte Passwortänderung')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Benutzer',
                'verbose_name_plural': 'Benutzer',
                'db_table': 'users_user',
                'ordering': ['last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('city', models.CharField(max_length=100, verbose_name='Stadt')),
                ('postal_code', models.CharField(max_length=10, verbose_name='PLZ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Gelöscht')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL, verbose_name='Standortleitung')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'db_table': 'users_location',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.location', verbose_name='Standort'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['location'], name='users_user_locatio_2b76cf_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['organization'], name='users_locat_organiz_548aa1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['manager'], name='users_locat_manager_08ff2f_idx'),
        ),
    ]
