# Generated by Django 5.2.12 on 2026-03-25 15:44

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(max_length=255, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='Telefon'),
        ),
    ]
