# Generated by Django 5.2.12 on 2026-03-25 16:09

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_users_user_email_6f2530_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=encrypted_fields.fields.EncryptedEmailField(blank=True, default='', max_length=255, null=True, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='PLZ'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Straße'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Telefon'),
        ),
    ]
