# Generated by Django 5.2.12 on 2026-03-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_is_2fa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Nutzungsbedingungen akzeptiert'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nutzungsbedingungen akzeptiert am'),
        ),
    ]
