# Generated by Django 5.2.12 on 2026-03-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_terms_acceptance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Anonymisiert am'),
        ),
    ]
