# Generated by Django 5.2.12 on 2026-03-27 07:52

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_anonymized_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('main', 'Hauptmandant'), ('sub', 'Untermandant')], default='sub', max_length=10, verbose_name='Organisationstyp'),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leer fuer Hauptmandanten. Verweist auf den Hauptmandanten fuer Untermandanten.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.organization', verbose_name='Uebergeordnete Organisation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(default='Oesterreich', max_length=100, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Geloescht'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='street',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, default='', max_length=255, null=True, verbose_name='Strasse'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['parent'], name='users_organ_parent__da088b_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['org_type'], name='users_organ_org_typ_1d7551_idx'),
        ),
    ]
