# Generated by Django 5.2.12 on 2026-03-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_organization_org_type_organization_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='PLZ'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['city'], name='users_locat_city_bca050_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='users_locat_name_602bff_idx'),
        ),
    ]
