# Generated by Django 5.2.12 on 2026-03-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0008_location_city_postal_unencrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Direkte Organisationszuordnung (primaer fuer Admin-Rolle). Fuer Educators/LocationManager wird die Organisation ueber den Standort aufgeloest.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_direct', to='core.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='users_user_organiz_41bb37_idx'),
        ),
    ]
