# Generated by Django 5.2.12 on 2026-03-30 08:07

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_organization_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/', validators=[core.validators.FileTypeValidator({'image/gif': ['.gif'], 'image/jpeg': ['.jpg', '.jpeg'], 'image/png': ['.png'], 'image/svg+xml': ['.svg'], 'image/webp': ['.webp']}), core.validators.FileSizeValidator(5242880)], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[core.validators.FileTypeValidator({'image/gif': ['.gif'], 'image/jpeg': ['.jpg', '.jpeg'], 'image/png': ['.png'], 'image/svg+xml': ['.svg'], 'image/webp': ['.webp']}), core.validators.FileSizeValidator(5242880)], verbose_name='Profilbild'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('educator', 'Pädagogin'), ('location_manager', 'Standortleitung'), ('sub_admin', 'Sub-Mandanten-Admin'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], default='educator', max_length=20, verbose_name='Rolle'),
        ),
    ]
